2024-02-24 22:13:56,184 ERROR: [404] Error while retrieving live attendance. Exception: list.remove(x): x not in list [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-02-24 22:25:02,709 ERROR: [404] Error while chosing training model. Exception: unsupported operand type(s) for &: 'str' and 'int' [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-02-26 16:44:24,485 ERROR: [404] Error file too big. Exception:  [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-02-26 16:54:38,050 ERROR: [413] Error file too big for the model selected. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-04-24 17:58:25,645 ERROR: [409] Error while creating user. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-04-24 18:06:31,438 ERROR: [422] Error while creating user. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-04-24 18:06:38,212 ERROR: [422] Error while creating user. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-04-24 18:06:58,113 ERROR: [422] Error while creating user. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-04-24 18:08:12,978 ERROR: [422] Error while creating user. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-04-24 18:09:16,777 ERROR: [422] Error while creating user. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-04-25 00:13:44,372 ERROR: [409] Error while creating user. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-04-25 01:20:17,119 ERROR: [409] Error while creating user. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-04-25 17:40:21,500 ERROR: [409] Error while creating user. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-02 17:34:16,212 ERROR: [409] Error while creating user. Exception: [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-02 23:21:57,122 ERROR: [500] Error while creating user. Exception: Object of type set is not JSON serializable [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-02 23:30:05,335 ERROR: [500] Error while creating user. Exception: Object of type set is not JSON serializable [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-02 23:40:16,876 ERROR: [500] Error while creating user. Exception: Object of type set is not JSON serializable [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-02 23:40:32,705 ERROR: [500] Error while creating user. Exception: Object of type set is not JSON serializable [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-02 23:40:38,589 ERROR: [500] Error while creating user. Exception: Object of type set is not JSON serializable [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-02 23:45:05,723 ERROR: [500] Error while creating user. Exception: Object of type set is not JSON serializable [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-02 23:45:25,613 ERROR: [500] Error while creating user. Exception: Object of type set is not JSON serializable [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-02 23:47:30,198 ERROR: [500] Error while creating user. Exception: Object of type set is not JSON serializable [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-02 23:50:21,953 ERROR: [500] Error while creating user. Exception: Object of type set is not JSON serializable [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-03 22:50:52,457 ERROR: [500] Error while logging in. Exception: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-03 22:50:56,145 ERROR: [500] Error while logging in. Exception: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-04 00:40:52,787 ERROR: [500] Error while logging in. Exception: 'str' object has no attribute 'set_cookie' [in C:\Users\yassi\Desktop\Housing_Datasets\api\utility\error_handlers.py:22]
2024-05-16 15:25:02,415 ERROR: [500] Error while predicting value. Exception: 'NoneType' object is not subscriptable [in C:\Users\yassi\Desktop\Housing_Valuation\backend\api\utility\error_handlers.py:26]
2024-05-16 15:32:46,034 ERROR: [500] Error while predicting value. Exception: 'NoneType' object is not subscriptable [in C:\Users\yassi\Desktop\Housing_Valuation\backend\api\utility\error_handlers.py:26]
2024-05-16 15:33:32,041 ERROR: [500] Error while predicting value. Exception: 'NoneType' object is not subscriptable [in C:\Users\yassi\Desktop\Housing_Valuation\backend\api\utility\error_handlers.py:26]
2024-05-16 15:58:09,312 ERROR: [500] Error while predicting value. Exception: 'NoneType' object is not subscriptable [in C:\Users\yassi\Desktop\Housing_Valuation\backend\api\utility\error_handlers.py:26]
2024-05-16 16:00:11,953 ERROR: [500] Error while predicting value. Exception: object of type 'NoneType' has no len() [in C:\Users\yassi\Desktop\Housing_Valuation\backend\api\utility\error_handlers.py:26]
2024-05-16 16:00:28,332 ERROR: [500] Error while predicting value. Exception: object of type 'NoneType' has no len() [in C:\Users\yassi\Desktop\Housing_Valuation\backend\api\utility\error_handlers.py:26]
